
hi i have :

from django.core.exceptions import ValidationError

def validate_image(value):
    if not value.name.lower().endswith(('.png', '.jpg', '.jpeg', '.gif')):
        raise ValidationError("Only image files (.png, .jpg, .jpeg, .gif) are allowed.")





and the follwin model :

class ProjectTypeExtraImages(models.Model):
    project_type = models.ForeignKey(ProjectType, related_name='ProjectTypeExtraImages_project_type_related_ProjectType', on_delete=models.CASCADE, blank=True, null=True)
    file = models.FileField(upload_to='ProjectType/ProjectTypeExtraImages/', validators=[validate_image])
    file_name = models.CharField(max_length=255, editable=False, null=True, blank=True)
    created_data = models.DateTimeField(auto_now_add=True) 

    def save(self, *args, **kwargs):
        if self.file :
            self.file_name = basename(self.file.name)
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.id}, {self.file_name}" 


and the follwin serializer :


class ProjectTypeSerializer(serializers.ModelSerializer):
    extra_images = ProjectTypeExtraImagesSerializer(many=True, read_only=True, source="ProjectTypeExtraImages_project_type_related_ProjectType")
    attachments = ProjectTypeAttachmentSerializer(many=True, read_only=True,  source="ProjectTypeAttachment_project_name")

    class Meta:
        model = ProjectType
        fields = "__all__"
        read_only_fields = ["id", "project_slog", "created_date", "updated_date"]


    def create(self, validated_data):
        obj = super().create(validated_data)

        request = self.context.get('request')
        extra_image_files = request.FILES.getlist('extra_images[]')  if request else []
        
        extra_images_list = []
        for extra_image in extra_image_files:
            extra_image_obj = ProjectTypeExtraImages.objects.create( project_type=obj, file=extra_image)
            extra_images_list.append(extra_image_obj)




why when i use : ProjectTypeExtraImages.objects.create( project_type=obj, file=extra_image) , the "validate_image" not work and accept .pdf file ?